// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdc863Yx9Plkd75K-wLY28yluVm-dQiEY',
    appId: '1:746852229759:web:b79adb73e613593b0d554a',
    messagingSenderId: '746852229759',
    projectId: 'patios-de-retencion-vehi-a8ab7',
    authDomain: 'patios-de-retencion-vehi-a8ab7.firebaseapp.com',
    storageBucket: 'patios-de-retencion-vehi-a8ab7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsR1zfd7tXzPmao-dWoJCJN859C5QMm3w',
    appId: '1:746852229759:android:320b33d95ce55ea90d554a',
    messagingSenderId: '746852229759',
    projectId: 'patios-de-retencion-vehi-a8ab7',
    storageBucket: 'patios-de-retencion-vehi-a8ab7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIAjeC2aWh8xf1wN_Uenbl5m7858-yLPU',
    appId: '1:746852229759:ios:bb58c349d6940d070d554a',
    messagingSenderId: '746852229759',
    projectId: 'patios-de-retencion-vehi-a8ab7',
    storageBucket: 'patios-de-retencion-vehi-a8ab7.firebasestorage.app',
    androidClientId: '746852229759-ef4b0ta84bhot3akg9f65akepltqi3hc.apps.googleusercontent.com',
    iosClientId: '746852229759-caidhu9l668la9ht9sj85k48c7hs32ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.registrosPrvTransito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIAjeC2aWh8xf1wN_Uenbl5m7858-yLPU',
    appId: '1:746852229759:ios:bb58c349d6940d070d554a',
    messagingSenderId: '746852229759',
    projectId: 'patios-de-retencion-vehi-a8ab7',
    storageBucket: 'patios-de-retencion-vehi-a8ab7.firebasestorage.app',
    androidClientId: '746852229759-ef4b0ta84bhot3akg9f65akepltqi3hc.apps.googleusercontent.com',
    iosClientId: '746852229759-caidhu9l668la9ht9sj85k48c7hs32ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.registrosPrvTransito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdc863Yx9Plkd75K-wLY28yluVm-dQiEY',
    appId: '1:746852229759:web:80878666154b16c20d554a',
    messagingSenderId: '746852229759',
    projectId: 'patios-de-retencion-vehi-a8ab7',
    authDomain: 'patios-de-retencion-vehi-a8ab7.firebaseapp.com',
    storageBucket: 'patios-de-retencion-vehi-a8ab7.firebasestorage.app',
  );
}
